name: Test
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  x86-64-unit-tests:
    name: x86 Cargo unit tests
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install nightly-2023-06-01 --no-self-update --profile minimal
          rustup default nightly-2023-06-01

      - name: Cargo cache
        uses: ./.github/actions/cargo-cache

      - name: Cargo test
        run: cargo test --no-fail-fast